enum MESSAGE_TYPE {
    READY = 'READY',
    SESSIONS_REPLACE = 'SESSIONS_REPLACE',
    READY_SUPPLEMENTAL = 'READY_SUPPLEMENTAL',
    MESSAGE_CREATE = 'MESSAGE_CREATE',
}

export default MESSAGE_TYPE