enum ActionTypes {
  UPDATE_URL = '@core/UPDATE_URL',
  UPDATE_TOKEN = '@core/UPDATE_TOKEN',
  UPDATE_SEQUENCE_NUMBER = '@core/UPDATE_SEQUENCE_NUMBER',
  UPDATE_RESUME_TOKEN = '@core/UPDATE_RESUME_TOKEN',
  UPDATE_ID = '@core/UPDATE_ID',
  UPDATE_USERNAME = '@core/UPDATE_USERNAME',
  UPDATE_CAPTCHA_REQUIRED = '@core/UPDATE_CAPTCHA_REQUIRED',
  UPDATE_OWO_CHANNEL_ID = '@core/UPDATE_OWO_CHANNEL_ID',
  UPDATE_CHANNEL_ID = '@core/UPDATE_CHANNEL_ID',
}

export default ActionTypes
